# Movies Dataset

In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv(r"D:\movies.csv")

In [3]:
df

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,-2021,"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,-2021,"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
9994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.shape

(9999, 9)

In [5]:
df.drop(df.index[500:9999],inplace = True)

In [6]:
df.shape

(500, 9)

In [7]:
df

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,-2021,"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,-2021,"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
495,La catedral del mar,-2018,"\nDrama, History",7.5,\nBased upon Ildefonso Falcones novel.,"\n \n Stars:\nJordi Aguilar, \nA...","3,574",55.0,NaN
496,Beckett,-2021,"\nAction, Crime, Drama",NaN,"\nFollowing a tragic car accident in Greece, B...",\n Director:\nFerdinando Cito Filomarino\n|...,NaN,108.0,NaN
497,Triple Frontier,-2019,"\nAction, Adventure, Crime",6.4,\nLoyalties are tested when five friends and f...,\n Director:\nJ.C. Chandor\n| \n Stars:\...,"115,059",125.0,NaN
498,Fondeados,-2021,\nComedy,4.2,\nTwo directionless millennial bros get high a...,\n Director:\nMarcos Bucay\n| \n Stars:\...,161,97.0,NaN
499,Sweet Home,(2020– ),"\nDrama, Fantasy, Horror",7.4,"\nHyun, a loner high school student who lost h...","\n \n Stars:\nSong Kang, \nLee J...","12,428",52.0,NaN

In [8]:
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,-2021,"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,-2021,"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN

In [9]:
df.tail()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
495,La catedral del mar,-2018,"\nDrama, History",7.5,\nBased upon Ildefonso Falcones novel.,"\n \n Stars:\nJordi Aguilar, \nA...","3,574",55.0,NaN
496,Beckett,-2021,"\nAction, Crime, Drama",NaN,"\nFollowing a tragic car accident in Greece, B...",\n Director:\nFerdinando Cito Filomarino\n|...,NaN,108.0,NaN
497,Triple Frontier,-2019,"\nAction, Adventure, Crime",6.4,\nLoyalties are tested when five friends and f...,\n Director:\nJ.C. Chandor\n| \n Stars:\...,"115,059",125.0,NaN
498,Fondeados,-2021,\nComedy,4.2,\nTwo directionless millennial bros get high a...,\n Director:\nMarcos Bucay\n| \n Stars:\...,161,97.0,NaN
499,Sweet Home,(2020– ),"\nDrama, Fantasy, Horror",7.4,"\nHyun, a loner high school student who lost h...","\n \n Stars:\nSong Kang, \nLee J...","12,428",52.0,NaN

In [10]:
df = df.drop(['Gross'],axis=1)

In [11]:
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime
0,Blood Red Sky,-2021,"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0
4,Army of Thieves,-2021,"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN

In [12]:
df.columns

Index(['MOVIES', 'YEAR', 'GENRE', 'RATING', 'ONE-LINE', 'STARS', 'VOTES',
       'RunTime'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MOVIES    500 non-null    object
 1   YEAR      500 non-null    object
 2   GENRE     500 non-null    object
 3   RATING    490 non-null    float64
 4   ONE-LINE  500 non-null    object
 5   STARS     500 non-null    object
 6   VOTES     490 non-null    object
 7   RunTime   478 non-null    float64
dtypes: float64(2), object(6)
memory usage: 31.4+ KB

In [14]:
df['MOVIES']

0                            Blood Red Sky
1      Masters of the Universe: Revelation
2                         The Walking Dead
3                           Rick and Morty
4                          Army of Thieves
                      ...
495                    La catedral del mar
496                                Beckett
497                        Triple Frontier
498                              Fondeados
499                             Sweet Home
Name: MOVIES, Length: 500, dtype: object

In [15]:
df['MOVIES'] = df['MOVIES'].str.replace('r\W',' ')

C:\Users\user\AppData\Local\Temp\ipykernel_5488\1889730094.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['MOVIES'] = df['MOVIES'].str.replace('r\W',' ')

In [16]:
df['MOVIES'].head()

0                          Blood Red Sky
1    Masters of the Universe: Revelation
2                       The Walking Dead
3                         Rick and Morty
4                        Army of Thieves
Name: MOVIES, dtype: object

In [17]:
df['YEAR']

0            -2021
1         (2021– )
2      (2010–2022)
3         (2013– )
4            -2021
          ...
495          -2018
496          -2021
497          -2019
498          -2021
499       (2020– )
Name: YEAR, Length: 500, dtype: object

In [18]:
df['YEAR'] = df['YEAR'].str.replace(r'[\W_\(\)-]',' ')

C:\Users\user\AppData\Local\Temp\ipykernel_5488\2406899296.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['YEAR'] = df['YEAR'].str.replace(r'[\W_\(\)-]',' ')

In [19]:
df['YEAR']

0             2021
1          2021
2       2010 2022
3          2013
4             2021
          ...
495           2018
496           2021
497           2019
498           2021
499        2020
Name: YEAR, Length: 500, dtype: object

In [20]:
df['GENRE'] = df['GENRE'].str.replace(r'[\n ,]',' ')

C:\Users\user\AppData\Local\Temp\ipykernel_5488\3673625797.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['GENRE'] = df['GENRE'].str.replace(r'[\n ,]',' ')

In [21]:
df['GENRE']

0           Action  Horror  Thriller
1       Animation  Action  Adventure
2            Drama  Horror  Thriller
3       Animation  Adventure  Comedy
4              Action  Crime  Horror
                         ...
495                   Drama  History
496             Action  Crime  Drama
497         Action  Adventure  Crime
498                           Comedy
499           Drama  Fantasy  Horror
Name: GENRE, Length: 500, dtype: object

In [22]:
df['ONE-LINE']

0      \nA woman with a mysterious illness is forced ...
1      \nThe war for Eternia begins again in what may...
2      \nSheriff Deputy Rick Grimes wakes up from a c...
3      \nAn animated series that follows the exploits...
4      \nA prequel, set before the events of Army of ...
                             ...
495               \nBased upon Ildefonso Falcones novel.
496    \nFollowing a tragic car accident in Greece, B...
497    \nLoyalties are tested when five friends and f...
498    \nTwo directionless millennial bros get high a...
499    \nHyun, a loner high school student who lost h...
Name: ONE-LINE, Length: 500, dtype: object

In [23]:
df['ONE-LINE'] = df['ONE-LINE'].str.replace(r'[\n]','')

C:\Users\user\AppData\Local\Temp\ipykernel_5488\813719331.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['ONE-LINE'] = df['ONE-LINE'].str.replace(r'[\n]','')

In [24]:
df['ONE-LINE']

0      A woman with a mysterious illness is forced in...
1      The war for Eternia begins again in what may b...
2      Sheriff Deputy Rick Grimes wakes up from a com...
3      An animated series that follows the exploits o...
4      A prequel, set before the events of Army of th...
                             ...
495                 Based upon Ildefonso Falcones novel.
496    Following a tragic car accident in Greece, Bec...
497    Loyalties are tested when five friends and for...
498    Two directionless millennial bros get high and...
499    Hyun, a loner high school student who lost his...
Name: ONE-LINE, Length: 500, dtype: object

In [25]:
df.rename(columns={'STARS':'CAST&CREW'},inplace = True)

In [26]:
df.columns

Index(['MOVIES', 'YEAR', 'GENRE', 'RATING', 'ONE-LINE', 'CAST&CREW', 'VOTES',
       'RunTime'],
      dtype='object')

In [27]:
df['CAST&CREW'] = df['CAST&CREW'].str.replace(r'[\n]','')

C:\Users\user\AppData\Local\Temp\ipykernel_5488\1716076231.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['CAST&CREW'] = df['CAST&CREW'].str.replace(r'[\n]','')

In [28]:
df['CAST&CREW']

0          Director:Peter Thorwarth|     Stars:Peri B...
1                      Stars:Chris Wood, Sarah Michel...
2                      Stars:Andrew Lincoln, Norman R...
3                      Stars:Justin Roiland, Chris Pa...
4          Director:Matthias Schweighöfer|     Stars:...
                             ...
495                    Stars:Jordi Aguilar, Aitor Lun...
496        Director:Ferdinando Cito Filomarino|     S...
497        Director:J.C. Chandor|     Stars:Ben Affle...
498        Director:Marcos Bucay|     Stars:Aldo Esca...
499                    Stars:Song Kang, Lee Jin-Wook,...
Name: CAST&CREW, Length: 500, dtype: object

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   MOVIES     500 non-null    object
 1   YEAR       500 non-null    object
 2   GENRE      500 non-null    object
 3   RATING     490 non-null    float64
 4   ONE-LINE   500 non-null    object
 5   CAST&CREW  500 non-null    object
 6   VOTES      490 non-null    object
 7   RunTime    478 non-null    float64
dtypes: float64(2), object(6)
memory usage: 31.4+ KB

In [30]:
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,CAST&CREW,VOTES,RunTime
0,Blood Red Sky,2021,Action Horror Thriller,6.1,A woman with a mysterious illness is forced in...,Director:Peter Thorwarth| Stars:Peri B...,"21,062",121.0
1,Masters of the Universe: Revelation,2021,Animation Action Adventure,5.0,The war for Eternia begins again in what may b...,"Stars:Chris Wood, Sarah Michel...","17,870",25.0
2,The Walking Dead,2010 2022,Drama Horror Thriller,8.2,Sheriff Deputy Rick Grimes wakes up from a com...,"Stars:Andrew Lincoln, Norman R...","885,805",44.0
3,Rick and Morty,2013,Animation Adventure Comedy,9.2,An animated series that follows the exploits o...,"Stars:Justin Roiland, Chris Pa...","414,849",23.0
4,Army of Thieves,2021,Action Crime Horror,NaN,"A prequel, set before the events of Army of th...",Director:Matthias Schweighöfer| Stars:...,NaN,NaN

In [31]:
df['VOTES']=df['VOTES'].str.replace(',','')

In [32]:
clean_data = df.copy()

In [33]:
clean_data.isnull().sum()

MOVIES        0
YEAR          0
GENRE         0
RATING       10
ONE-LINE      0
CAST&CREW     0
VOTES        10
RunTime      22
dtype: int64

In [34]:
# Dealing with Missing value

In [35]:
clean_data['RATING'] = clean_data['RATING'].fillna(np.mean(pd.to_numeric(clean_data['RATING']))).round(2)

In [36]:
clean_data

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,CAST&CREW,VOTES,RunTime
0,Blood Red Sky,2021,Action Horror Thriller,6.10,A woman with a mysterious illness is forced in...,Director:Peter Thorwarth| Stars:Peri B...,21062,121.0
1,Masters of the Universe: Revelation,2021,Animation Action Adventure,5.00,The war for Eternia begins again in what may b...,"Stars:Chris Wood, Sarah Michel...",17870,25.0
2,The Walking Dead,2010 2022,Drama Horror Thriller,8.20,Sheriff Deputy Rick Grimes wakes up from a com...,"Stars:Andrew Lincoln, Norman R...",885805,44.0
3,Rick and Morty,2013,Animation Adventure Comedy,9.20,An animated series that follows the exploits o...,"Stars:Justin Roiland, Chris Pa...",414849,23.0
4,Army of Thieves,2021,Action Crime Horror,7.41,"A prequel, set before the events of Army of th...",Director:Matthias Schweighöfer| Stars:...,NaN,NaN
...,...,...,...,...,...,...,...,...
495,La catedral del mar,2018,Drama History,7.50,Based upon Ildefonso Falcones novel.,"Stars:Jordi Aguilar, Aitor Lun...",3574,55.0
496,Beckett,2021,Action Crime Drama,7.41,"Following a tragic car accident in Greece, Bec...",Director:Ferdinando Cito Filomarino| S...,NaN,108.0
497,Triple Frontier,2019,Action Adventure Crime,6.40,Loyalties are tested when five friends and for...,Director:J.C. Chandor| Stars:Ben Affle...,115059,125.0
498,Fondeados,2021,Comedy,4.20,Two directionless millennial bros get high and...,Director:Marcos Bucay| Stars:Aldo Esca...,161,97.0
499,Sweet Home,2020,Drama Fantasy Horror,7.40,"Hyun, a loner high school student who lost his...","Stars:Song Kang, Lee Jin-Wook,...",12428,52.0

In [39]:
clean_data['VOTES'] = clean_data['VOTES'].astype(float)

In [42]:
clean_data['VOTES'] = clean_data['VOTES'].fillna(np.mean(pd.to_numeric(clean_data['VOTES'])))

In [43]:
clean_data.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,CAST&CREW,VOTES,RunTime
0,Blood Red Sky,2021,Action Horror Thriller,6.10,A woman with a mysterious illness is forced in...,Director:Peter Thorwarth| Stars:Peri B...,21062.00,121.0
1,Masters of the Universe: Revelation,2021,Animation Action Adventure,5.00,The war for Eternia begins again in what may b...,"Stars:Chris Wood, Sarah Michel...",17870.00,25.0
2,The Walking Dead,2010 2022,Drama Horror Thriller,8.20,Sheriff Deputy Rick Grimes wakes up from a com...,"Stars:Andrew Lincoln, Norman R...",885805.00,44.0
3,Rick and Morty,2013,Animation Adventure Comedy,9.20,An animated series that follows the exploits o...,"Stars:Justin Roiland, Chris Pa...",414849.00,23.0
4,Army of Thieves,2021,Action Crime Horror,7.41,"A prequel, set before the events of Army of th...",Director:Matthias Schweighöfer| Stars:...,155778.15,NaN

In [48]:
clean_data['RunTime'] = clean_data['RunTime'].fillna(np.mean(pd.to_numeric(clean_data['RunTime']))).round(2)

In [49]:
clean_data.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,CAST&CREW,VOTES,RunTime
0,Blood Red Sky,2021,Action Horror Thriller,6.10,A woman with a mysterious illness is forced in...,Director:Peter Thorwarth| Stars:Peri B...,21062.00,121.00
1,Masters of the Universe: Revelation,2021,Animation Action Adventure,5.00,The war for Eternia begins again in what may b...,"Stars:Chris Wood, Sarah Michel...",17870.00,25.00
2,The Walking Dead,2010 2022,Drama Horror Thriller,8.20,Sheriff Deputy Rick Grimes wakes up from a com...,"Stars:Andrew Lincoln, Norman R...",885805.00,44.00
3,Rick and Morty,2013,Animation Adventure Comedy,9.20,An animated series that follows the exploits o...,"Stars:Justin Roiland, Chris Pa...",414849.00,23.00
4,Army of Thieves,2021,Action Crime Horror,7.41,"A prequel, set before the events of Army of th...",Director:Matthias Schweighöfer| Stars:...,155778.15,80.17

In [50]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   MOVIES     500 non-null    object
 1   YEAR       500 non-null    object
 2   GENRE      500 non-null    object
 3   RATING     500 non-null    float64
 4   ONE-LINE   500 non-null    object
 5   CAST&CREW  500 non-null    object
 6   VOTES      500 non-null    float64
 7   RunTime    500 non-null    float64
dtypes: float64(3), object(5)
memory usage: 31.4+ KB

In [51]:
clean_data.isnull().sum()

MOVIES       0
YEAR         0
GENRE        0
RATING       0
ONE-LINE     0
CAST&CREW    0
VOTES        0
RunTime      0
dtype: int64

In [66]:
columns = clean_data.columns
for i in columns:
    if  clean_data[i].dtype==('object'):
         clean_data[i]=clean_data[i].astype('category')

In [64]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   MOVIES     500 non-null    category
 1   YEAR       500 non-null    category
 2   GENRE      500 non-null    category
 3   RATING     500 non-null    float64
 4   ONE-LINE   500 non-null    category
 5   CAST&CREW  500 non-null    category
 6   VOTES      500 non-null    float64
 7   RunTime    500 non-null    float64
dtypes: category(5), float64(3)
memory usage: 87.5 KB

In [77]:
file_path = r"C:\Users\user\Cleandata.csv"
clean_data.to_csv(file_path,index=False)

# Completed......